version: "3.7"

networks:
  keycloak_network:

volumes:
  keycloak-themes:
  postgres:

services:
  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: ${SERVICE_NAME:-keycloak}-${ENV_NAME:-test}
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    env_file:
      - .env
    volumes:
      - keycloak-themes:/opt/jboss/keycloak/themes
    depends_on:
      - postgres
    networks:
      - keycloak_network

  postgres:
    image: postgres:alpine3.16
    container_name: ${SERVICE_NAME:-keycloak}-postgres-${ENV_NAME:-test}
    env_file:
      - .env
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: on-failure
    networks:
      - keycloak_network

  login:
    image: ${SERVICE_NAME:-keycloak}:${ENV_NAME:-test}
    container_name: ${SERVICE_NAME:-keycloak}-front-end-${ENV_NAME:-test}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${LOGIN_PORT:-80}:80
    restart: on-failure
    depends_on:
      - keycloak
    networks:
      - keycloak_network