version: "3"
services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "DB_VENDOR=H2"

  front-end:
    container_name: keycloak-app
    image: keycloak-app
    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - 8000:80
    
    restart: always
